# Numpy

https://numpy.org/

## What is it? 
- Numpy is a Python library used for working with arrays
- Numpy is the fundamental package for scientific computing in Python


## Why do we care? 
- Numpy is one of the main reasons why Python is so powerful and popular for scientific computing
- Super fast. Numpy arrays are implemented in C, which makes numpy very fast.
- The arrays allows for vectorized operations

## Show us! 

### Create a 1D array

#### create a list
format: list()

In [1]:
#create a list
my_list = [1, 2, 3, 4]
my_list

[1, 2, 3, 4]

In [2]:
#whats the type
type(my_list)

list

In [4]:
#what is dtype
#my_list.dtype

In [6]:
#whats the shape
#list.shape

#### create an array
format: np.array()

In [7]:
#import numpy
import numpy as np

In [9]:
#create the array
my_array = np.array(my_list)
my_array

array([1, 2, 3, 4])

In [14]:
#whats the type
type(my_array)

numpy.ndarray

In [15]:
#whats the shape
my_array.shape

(4,)

In [16]:
#whats the dtype
my_array.dtype

dtype('int64')

#### access elements of our new array

In [19]:
my_array

array([1, 2, 3, 4])

In [18]:
my_array[0]

1

In [20]:
my_array[-1]

4

#### slice the array

In [21]:
my_array[1:]

array([2, 3, 4])

In [22]:
my_array[:2] 

array([1, 2])

#### create an array from 1 to 100

In [24]:
#np.array(?)
a = np.array(range(1, 101))
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [25]:
#access single element
a[-1]

100

In [26]:
#slice the array! 
a[25:]

array([ 26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [27]:
a[5:16]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

### Create a 2D array

In [28]:
#build a list of lists
matrix = [[1, 2, 3],
[2, 3, 4],
[6, 7, 8]]
matrix

[[1, 2, 3], [2, 3, 4], [6, 7, 8]]

In [29]:
type(matrix)

list

In [30]:
#turn it into an array! 
matrix_array = np.array(matrix)
matrix_array

array([[1, 2, 3],
       [2, 3, 4],
       [6, 7, 8]])

In [31]:
#type
type(matrix_array)

numpy.ndarray

In [32]:
matrix_array.shape

(3, 3)

In [33]:
matrix_array.dtype

dtype('int64')

#### access elements

In [34]:
matrix_array

array([[1, 2, 3],
       [2, 3, 4],
       [6, 7, 8]])

In [35]:
matrix_array[0]

array([1, 2, 3])

In [36]:
matrix_array[-1]

array([6, 7, 8])

In [37]:
matrix_array[0][0]

1

In [39]:
matrix_array[0,0]

1

In [41]:
matrix_array[2, 1]

7

### Descriptive Stats

In [42]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

### using methods: the method is called on the numpy object

#### format: object.method()

In [43]:
a.min()

1

In [44]:
a.max()

100

In [47]:
a.mean()

50.5

In [49]:
a.std() #standard deviation

28.86607004772212

In [51]:
matrix_array.min()

1

In [52]:
matrix_array.mean()

4.0

In [54]:
matrix_array.max()

8

#### using functions: using numpy to call functions

In [213]:
np.max(a)

100

In [214]:
np.std(a)

28.86607004772212

In [215]:
np.mean(a)

50.5

In [216]:
np.sum(a)

5050

### Array of Booleans! 

### Boolean Masks

1. create an array
2. make a list of booleans (mask)
3. combine

    format: array [ list of booleans ] 

In [55]:
#pull back our small array
my_array

array([1, 2, 3, 4])

In [56]:
#make list of booleans aka our mask
mask = [True, False, False, True]
mask

[True, False, False, True]

In [58]:
#combine them 
my_array[mask] # only returns values that are identified as 'True' in the list of bools we made named 'mask'

array([1, 4])

#### how else can we get our array of boolean values?

In [59]:
my_array

array([1, 2, 3, 4])

In [60]:
#write a conditional with the array
my_array == 4

array([False, False, False,  True])

In [61]:
mask = (my_array ==4)
mask

array([False, False, False,  True])

In [62]:
my_array[mask]

array([4])

In [63]:
mask = my_array > 2
mask

array([False, False,  True,  True])

In [64]:
#format: array_name [list_of_booleans]
my_array[mask]

array([3, 4])

In [69]:
#use the & instead of AND 
#use the | instead of OR

### do it with a matrix!

In [65]:
matrix_array > 3

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [67]:
mask = (matrix_array > 3)
mask

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [68]:
matrix_array[mask]

array([4, 6, 7, 8])

#### make and apply our boolean mask

array([False, False, False,  True, False])

In [485]:
#format: array_name [ list_of_booleans ]


#### cool! can we just do it with a list instead of an array?

In [70]:
#pull back our initial list
my_list

[1, 2, 3, 4]

In [73]:
#create a array of booleans
my_list == 4 #returns false

False

In [74]:
#apply an array of booleans to a list
my_list[mask]

TypeError: only integer scalar arrays can be converted to a scalar index

#### let's bring it back to arrays and make them bigger

In [75]:
#array
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [79]:
#mask
mask = a >= 90
mask

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [80]:
#boolean mask
a[mask]

array([ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

#### shortcut?

In [82]:
a[a >= 90]

array([ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [83]:
a[a == 4]

array([4])

#### what if we wanted to check two conditions?

In [88]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [89]:
# note the parenthesis
# also note that we're using & instead of and
mask = (a > 5) & (a < 15)
mask

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [90]:
a[mask]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

#### what if we wanted the opposite of our mask?

In [91]:
~mask

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [93]:
# the ~ notates the opposite of mask
a[mask]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [94]:
a[~mask]

array([  1,   2,   3,   4,   5,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

#### covert list of arrays to single list

In [92]:
new_list = []

for x in list(matrix_array):
    new_list.extend(x)
    
new_list   

[1, 2, 3, 2, 3, 4, 6, 7, 8]

## Vectorization Operations
- makes looping over math so easy and fast!

### Add one to every element

#### hard way: doing it in a list

In [100]:
my_list = [1, 2, 3, 4]

In [102]:
#using a for loop

new_list = []

for x in my_list:
    new_list.append(x+1)
new_list

[2, 3, 4, 5]

In [103]:
#using a list comprehension
[x+1 for x in my_list]

[2, 3, 4, 5]

#### easy way: doing it with an array

In [106]:
#using vectorization operations
my_array + 1

array([2, 3, 4, 5])

### more operations

In [107]:
my_array * 2

array([2, 4, 6, 8])

In [108]:
my_array / 10

array([0.1, 0.2, 0.3, 0.4])

In [109]:
my_array/10 + 2

array([2.1, 2.2, 2.3, 2.4])

In [110]:
np.log(my_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

### show us the speed

In [115]:
#make a really big array
big_array = np.array(range(1000001))
big_array

array([      0,       1,       2, ...,  999998,  999999, 1000000])

In [117]:
%%timeit

big_array ** 2

589 µs ± 19.4 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [120]:
#make a really big list
big_list = list(big_array)
big_list[:10]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [121]:
%%timeit

for x in big_list:
    x**2

75.3 ms ± 561 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


## Numpy ways to create arrays

#### full of zeros

In [122]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [123]:
np.zeros((10)) + 1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [124]:
np.zeros((10,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

#### full of ones

In [125]:
np.ones(5)

array([1., 1., 1., 1., 1.])

#### full of whatever you want 

In [129]:
# format: np.full(how many, what number)

np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

#### a quicker way to make a range

In [130]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [131]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [132]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### an array of random integers

In [152]:
#np.random.randint()

np.random.randint(1,100) #returns a random number from (first-number, second-number)

49

#### an array of random numbers from the standard distribution

In [153]:
np.random.randn(10)


array([-1.06520227, -0.82686039, -0.580055  ,  0.56815129,  2.06259044,
       -0.13386677, -1.6105506 ,  1.23475831,  0.70759059, -0.22916161])