## Numpy Exercises
#### Use the following code for the questions below:

In [2]:
import numpy as np

In [31]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

#### How many negative numbers are there?

In [18]:
mask = (a < 0)
len(a[mask])

4

#### How many positive numbers are there?

In [19]:
mask = (a > 0)
len(a[mask])

5

#### How many even positive numbers are there?

In [26]:
mask = (a > 0) & (a % 2 == 0)
len(a[mask])

3

#### If you were to add 3 to each data point, how many positive numbers would there be?

In [34]:
b = a + 3
mask = (b > 0)
print(b)
len(b[mask])

[ 7 13 15 26  1  2  3  3  3 -3  6 -4]


10

#### If you squared each number, what would the new mean and standard deviation be?

In [37]:
c = a ** 2
print(c.mean())
print(c.std())

74.0
144.0243035046516


#### A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set.

In [41]:
a.mean()

3.0

In [42]:
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [40]:
center = a.mean() - a
center

array([ -1.,  -7.,  -9., -20.,   5.,   4.,   3.,   3.,   3.,   9.,   0.,
        10.])

In [43]:
center.mean()

0.0

#### Calculate the z-score for each data point. Recall that the z-score is given by:

- Z
- =
- x
- −
- μ
- σ

In [48]:
mean = a.mean()
#mean
print((a - mean)/a.std())

[ 0.12403473  0.86824314  1.11631261  2.48069469 -0.62017367 -0.49613894
 -0.3721042  -0.3721042  -0.3721042  -1.11631261  0.         -1.24034735]


In [49]:
## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [52]:
sum_of_a = np.sum(a)
sum_of_a

55

In [ ]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [53]:
min_of_a = np.min(a)
min_of_a

1

In [ ]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [54]:
max_of_a = np.max(a)
max_of_a

10

In [ ]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [55]:
mean_of_a = np.mean(a)
mean_of_a

5.5

In [ ]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all 
# the numbers in the above list together

In [56]:
product_of_a = np.product(a)
product_of_a

3628800

In [ ]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number 
# in a squared like [1, 4, 9, 16, 25...]

In [63]:
squares_of_a = np.square(a)
squares_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

In [88]:
odds_in_a = np.mod(a, 2) != 0
odds_in_a

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [ ]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [89]:
evens_in_a = np.mod(a, 2) == 0
evens_in_a

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...

In [90]:
# Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, 
# and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [98]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. 
# **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)
sum_of_b

33

In [96]:
sum_of_b = np.sum(b)
sum_of_b

33

In [99]:
# Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  
min_of_b

3

In [100]:
min_of_b = np.min(b)
min_of_b

3

In [101]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])
max_of_b

8

In [102]:
max_of_b = np.max(b)
max_of_b

8

In [103]:
# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))
mean_of_b

5.5

In [104]:
mean_of_b = np.mean(b)
mean_of_b

5.5

In [105]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number
product_of_b

20160

In [107]:
product_of_b = np.product(b)
product_of_b

20160

In [108]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)
squares_of_b

[9, 16, 25, 36, 49, 64]

In [110]:
squares_of_b = np.square(b)
squares_of_b

array([[ 9, 16, 25],
       [36, 49, 64]])

In [116]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
            odds_in_b
odds_in_b

[3, 5, 7]

In [114]:
b_array = np.array(b)
odds_in_b = b_array[b_array % 2 != 0]
odds_in_b = odds_in_b.tolist()
odds_in_b

[3, 5, 7]

In [117]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
evens_in_b

[4, 6, 8]

In [118]:
b_array = np.array(b)
evens_in_b = b_array[b_array % 2 == 0]
evens_in_b = evens_in_b.tolist()
evens_in_b

[4, 6, 8]

In [ ]:
# Exercise 9 - print out the shape of the array b.

In [125]:
b_array = np.array(b)
print(b_array.shape)

(2, 3)


In [ ]:
# Exercise 10 - transpose the array b.

In [126]:
np.transpose(b_array)

array([[3, 6],
       [4, 7],
       [5, 8]])

In [ ]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

In [127]:
new_list = []

for x in list(b_array):
    new_list.extend(x)
    
new_list

[3, 4, 5, 6, 7, 8]

In [ ]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [166]:
reshaped_b = np.reshape(b_array, (6, 1))
reshaped_b

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [138]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [ ]:
# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
# Exercise 1 - Find the min, max, sum, and product of c.

In [140]:
print(np.min(c))
print(np.max(c))
print(np.sum(c))
print(np.product(c))

1
9
45
362880


In [ ]:
# Exercise 2 - Determine the standard deviation of c.

In [141]:
print(np.std(c))

2.581988897471611


In [ ]:
# Exercise 3 - Determine the variance of c.

In [142]:
print(np.var(c))

6.666666666666667


In [ ]:
# Exercise 4 - Print out the shape of the array c

In [143]:
c_array = np.array(c)
print(c_array.shape)

(3, 3)


In [ ]:
# Exercise 5 - Transpose c and print out transposed result.

In [144]:
np.transpose(c_array)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
# Exercise 6 - Get the dot product of the array c with c.

In [145]:
np.dot(c_array, c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [ ]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. 
# Answer should be 261

In [146]:
np.sum(c * np.transpose(c))

261

In [ ]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. 
# Answer should be 131681894400.

In [147]:
np.product(c * np.transpose(c))

131681894400

In [148]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

In [ ]:
# Exercise 1 - Find the sine of all the numbers in d

In [167]:
d_array = np.array(d)
np.sin(d_array)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [ ]:
# Exercise 2 - Find the cosine of all the numbers in d

In [150]:
np.cos(d_array)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [ ]:
# Exercise 3 - Find the tangent of all the numbers in d

In [151]:
np.tan(d_array)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [ ]:
# Exercise 4 - Find all the negative numbers in d

In [168]:
positive_d = d_array[d_array < 0]
positive_d 

array([-90, -30, -45, -45])

In [ ]:
# Exercise 5 - Find all the positive numbers in d

In [156]:
positive_d = d_array[d_array > 0]
positive_d 

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [ ]:
# Exercise 6 - Return an array of only the unique numbers in d.

In [157]:
unique_d = np.unique(d_array)
unique_d 

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [ ]:
# Exercise 7 - Determine how many unique numbers there are in d.

In [158]:
len(unique_d)

11

In [ ]:
# Exercise 8 - Print out the shape of d.

In [160]:
print(d_array.shape)

(3, 6)


In [ ]:
# Exercise 9 - Transpose and then print out the shape of d.

In [162]:
print((np.transpose(d).shape))


(6, 3)


In [ ]:
# Exercise 10 - Reshape d into an array of 9 x 2

In [163]:
reshaped_d = np.reshape(d_array, (9, 2))
reshaped_d

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])